apiVersion: v2
name: storage
description: A Helm chart for Kubernetes

type: application

# Helm chart Version

version: 0.1.0

keywords:
  - kubernetes
  - application
  - postgres
  - database

maintainers:
  - name: ndthang
    email: nthang621@gmail.com
