# values.yaml
namespace: shopnow

persistence:
  enabled: true
  pvName: "postgres-volume"
  pvcName: "postgres-volume-claim"
  type: "local"
  app: "postgres"
  pvStorageSize: "10Gi"
  storageSize: "5Gi"
  accessMode: "ReadWriteMany"
  storageClass: "nfs-storage"
  reclaimPolicy: "Retain"
  nfs:
    path: "/data/nfs-shared2/postgresql"
    server: "192.168.10.155"
  pvAnnotations: {}
  pvcAnnotations: {}
