apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/monitoring/prometheus
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
