applicationName: "discovery-server-shopnow"
namespaceOverride: "shopnow"

labels:
  group: com.ndthang.group
  team: ndthang

deployment:
  enabled: true
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  reloadOnChange: true
  replicas: 1
  image:
    repository: harbor.rnd.com/shopnow/discovery-server
    tag: v1
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: shopnow-registry-secret
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5
    requests:
      memory: 128Mi
      cpu: 0.1
  ports:
    - containerPort: 8761
      name: http
      protocol: TCP
  env:
    - name: SPRING_CONFIG_LOCATION
      value: "file:/app/config/application.properties"
  hostNetwork: false # Chỉ bật nếu thực sự cần
  volumeMounts:
    - name: config-volume
      mountPath: "/app/config"
  volumes:
    - name: config-volume
      configMap:
        name: "discovery-server-shopnow-application-properties-configmap"

configMap:
  enabled: true
  files:
    application-properties-configmap:
      application.properties: |
        spring.application.name=discovery-server
        server.port=8761
        eureka.client.register-with-eureka=false
        eureka.client.fetch-registry=false

service:
  enabled: true
  ports:
    - port: 8761
      name: http
      protocol: TCP
      targetPort: 8761
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: "{{ .Release.Name }}.ndthang.live"
      paths:
        - path: /
          pathType: "Prefix"
          serviceName: "discovery-server-shopnow"
          servicePort: 8761
