# values.yaml
application:
  name: shopnow-discovery-server
  namespace: shopnow

deployment:
  enabled: true
  replicas: 1
  revisionHistoryLimit: 11
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  image:
    repository: harbor.rnd.com/shopnow/discovery
    tag: v1
    pullPolicy: Always
  ports:
    - containerPort: 8761
      name: tcp
      protocol: TCP
  volumeMounts:
    shopnow-discovery-server-application-properties-config-volume:
      mountPath: /app/src/main/resources/application.properties
      subPath: application.properties
  volumes:
    shopnow-discovery-server-application-properties-config-volume:
      configMap:
        name: shopnow-discovery-server-application-properties-configmap
        defaultMode: 420
  imagePullSecrets:
    - name: shopnow-registry-secret
  dnsPolicy: ClusterFirst

configMap:
  enabled: true
  files:
    application-properties-configmap:
      application.properties: |
        spring.application.name=discovery-server
        server.port=8761
        eureka.client.register-with-eureka=false
        eureka.client.fetch-registry=false

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: tcp
      port: 8761
      protocol: TCP
      targetPort: 8761
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None

ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: discovery-server-shopnow.ndthang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopnow-discovery-server-service
                port:
                  number: 8761
