{{ if .Values.enabled }}

# Define PersistentVolume (PV)
{{- if or .Values.pvName .Values.nfs }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  labels:
    type: {{ .Values.type }}
    app: {{ .Values.app }}
  {{- if .Values.pvAnnotations }}
  annotations:
    {{ toYaml .Values.pvAnnotations | nindent 4 }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.pvStorageSize | quote }}
  accessModes:
    - {{ .Values.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.reclaimPolicy | quote }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- if .Values.nfs }}
  nfs:
    path: {{ .Values.nfs.path | quote }}
    server: {{ .Values.nfs.server | quote }}
  {{- end }}
{{- end }}

# Define PersistentVolumeClaim (PVC)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
  {{- if .Values.pvcAnnotations }}
  annotations:
    {{ toYaml .Values.pvcAnnotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storageSize | quote }}
  storageClassName: {{ .Values.storageClass | quote }}

{{- end }}