concurrent: 10

rbac:
  create: true
  clusterWideAccess: true # Đảm bảo quyền cluster-admin
  serviceAccountName: gitlab-runner-sa

runners:
  tags: "gitlab-runner-on-k8s, shopnow-k8s"
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine"
        image_pull_secrets = ["shopnow-registry-secret"]
        service-account = "gitlab-runner-sa"
        privileged = true
