gitlabUrl: "http://192.168.10.154"
runnerRegistrationToken: "glrt-t1_1tzyZWtHFd478BLEPXps"

concurrent: 10

rbac:
  create: true
  clusterWideAccess: true

runners:
  tags: "gitlab-runner-on-k8s, shopnow-k8s"
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine"
        service-account = "gitlab-runner-sa"
        privileged = true
