gitlabUrl: "http://192.168.10.159"
runnerRegistrationToken: "glrt-t1_yJMHr4Hz-RhkLbnRgnSo"

concurrent: 10

rbac:
  create: false
  clusterWideAccess: true # Đảm bảo quyền cluster-admin
  serviceAccountName: gitlab-runner-sa
serviceAccount:
  create: false
  name: gitlab-runner-sa

runners:
  tags: "gitlab-runner-on-k8s, shopnow-k8s"
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine"
        image_pull_secrets = ["shopnow-registry-secret"]
        service-account = "gitlab-runner-sa"
        privileged = true
