namespace: shopnow

# Cấu hình dependency pvc
pvc:
  enabled: true
  pvName: "postgres-volume"
  pvcName: "postgres-volume-claim"
  type: "local"
  app: "postgres"
  pvStorageSize: "10Gi"
  storageSize: "5Gi"
  accessMode: "ReadWriteMany"
  storageClass: "nfs-storage"
  reclaimPolicy: "Retain"
  nfs:
    path: "/data/nfs-shared2/postgresql"
    server: "192.168.10.155"

# Cấu hình cho PostgreSQL (Bitnami style)
architecture: standalone
replicaCount: 1

global:
  postgresql:
    auth:
      enablePostgresUser: true
      postgresPassword: "abcd456789"
      username: "postgres"
      password: "admin"
      database: "postgres"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""

primary:
  persistence:
    enabled: true
    existingClaim: "postgres-volume-claim"
    mountPath: /bitnami/postgresql
    accessModes:
      - ReadWriteMany
    size: 5Gi
  podManagementPolicy: "OrderedReady"
  terminationGracePeriodSeconds: 60
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  volumePermissions:
    enabled: true
