global:
  postgresql:
    auth:
      postgresPassword: "abcd456789"
      username: "postgres"
      password: "admin"
      database: "postgres"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""

primary:
  persistence:
    enabled: true
    existingClaim: "postgres-volume-claim"
    mountPath: /bitnami/postgresql
    accessModes:
      - ReadWriteMany
    size: 5Gi

  volumePermissions:
    enabled: true
