namespace: shopnow

# Cấu hình dependency pvc
pvc:
  enabled: true
  pvName: "postgres-volume"
  pvcName: "postgres-volume-claim"
  type: "local"
  app: "postgres"
  pvStorageSize: "10Gi"
  storageSize: "5Gi"
  accessMode: "ReadWriteMany"
  storageClass: "nfs-storage"
  reclaimPolicy: "Retain"
  nfs:
    path: "/mountdata/gluster/postgresql"
    server: "192.168.10.155"

# Cấu hình cho PostgreSQL (Bitnami style)
architecture: standalone
replicaCount: 1

global:
  postgresql:
    auth:
      enablePostgresUser: true
      postgresPassword: "abcd456789"
      username: "postgres"
      password: "admin"
      database: "postgres"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""

primary:
  persistence:
    enabled: true
    existingClaim: "postgres-volume-claim"
    mountPath: /bitnami/postgresql
    accessModes:
      - ReadWriteMany
    size: 5Gi
  podManagementPolicy: "OrderedReady"
  terminationGracePeriodSeconds: 60
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  volumePermissions:
    enabled: true

# CronJob backup
extraDeploy:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: postgresql-backup
      namespace: shopnow
    spec:
      schedule: "*/10 * * * *" # Backup evry 10 minutes
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: backup
                  image: bitnami/postgresql:17.4.0-debian-12-r8 # check ver in values postgresql
                  command:
                    - /bin/sh
                    - -c
                    - |
                      pg_dump -U postgres -h postgresql.shopnow.svc.cluster.local -d postgres > /backup/backup-$(date +%Y%m%d).sql && \
                      cp /backup/backup-$(date +%Y%m%d).sql /backup-dest/
                  env:
                    - name: PGPASSWORD
                      value: "abcd456789"
                  volumeMounts:
                    - name: backup-dest
                      mountPath: /backup-dest
              restartPolicy: OnFailure
              volumes:
                - name: backup-dest
                  persistentVolumeClaim:
                    claimName: backup-pvc # PVC để lưu trữ backup lâu dài
