# values.yaml
namespace: shopnow

persistence:
  enabled: true
  existingClaim: ""  # Không dùng PVC có sẵn để tạo mới
  pvName: "postgres-volume"
  pvcName: "postgres-volume-claim"
  type: "local"
  app: "postgres"
  pvStorageSize: "10Gi"
  storageSize: "5Gi"
  accessMode: "ReadWriteMany"
  storageClass: "nfs-storage"
  reclaimPolicy: "Retain"
  nfs:
    path: "/data/nfs-shared2/postgresql"
    server: "192.168.10.155"

# Cấu hình cho PostgreSQL
architecture: standalone
replicaCount: 1
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-volume-claim"  # Dùng PVC vừa tạo
    mountPath: /bitnami/postgresql
    size: 5Gi
    accessModes:
      - ReadWriteMany
volumePermissions:
  enabled: true
postgresql:
  username: "postgres"
  password: "admin"
  database: "postgres"
