apiVersion: v1
kind: Pod
metadata:
  name: my-debug
spec:
  containers:
    - name: my-debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - bphp-bch
