apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-0-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/mnt/es-0"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/mnt/es-1"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-2-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/mnt/es-2"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
