apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-postgresql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mountdata/gluster/postgresql/backup
    server: 192.168.10.155
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
  volumeMode: Filesystem
  volumeName: backup-postgresql-pv
