postgresql:
  enabled: false

externalDatabase:
  host: "postgres-keycloak-postgresql-hl.shopnow.svc.cluster.local"
  port: 5432
  user: bn_keycloak
  database: bitnami_keycloak
  password: "abcd456789"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak-shopnow.ndthang.live
  path: /
  tls: false

service:
  type: ClusterIP
  http:
    enabled: true
  ports:
    http: 8080
